### ISSUE TITLE
Function returning all leafs of tree/graph

### ISSUE THREAD

**Issue by ltbinsbe** [leegbestand/exploring_interpreters#1]
Zou je een functie kunnen toevoegen welke alle nodes oplevert welke geen uitgaande edges hebben?

Dus iets van type Explorer ... -> [(Ref, config)]

**Comment by leegbestand** [comment]
Dit is toegevoegd, zie d3a299d70b1a7e24c1793dfe914a6ff5726d84f8.
Als dit voldoende is, dan push ik het naar hackage.
